In [ ]:
import pandas as pd
import numpy as np

pd.set_option("display.max_columns", None)

In [3]:
df = pd.read_csv("hdfc_loan_dataset_full_enriched.csv")

df.head()

,Loan_ID,Bank,Customer_Name,Gender,Married,Dependents,Education,Employment_Status,Applicant_Income,Coapplicant_Income,Loan_Amount,Loan_Term_Months,Credit_History,Property_Area,Age,Loan_Status,CIBIL_Score,Annual_Household_Income,Debt_to_Income_Ratio,Purpose_of_Loan,Existing_EMIs,Number_of_Previous_Loans,Default_History_Count,Employment_Length_Years,Business_Type,Asset_Value,Guarantor,Co-signer_Relationship,Monthly_Expense,Organization_Type,Region_Branch,Mobile_Verified,Email_Verified,Institutional_Relationships,Application_Text,Customer_Feedback,Agent_Notes,Loan_to_Annual_Income,Customer_Sentiment,Religion,State,City,PIN_Code,Aadhaar_Synthetic,Phone_Number,Email,Occupation
0,HDFC100001,HDFC Bank,Rohan Verma,Male,No,2,Graduate,Salaried,56976,0,8031545,360,1,Urban,36,Approved,699,683712,0.098,Home,5610,0,0,1,NaN,744861,No,Friend,30391,Public,KOL-004,No,Yes,"RBI:Regulatory, NPCI:Payments integration, CIB...",Applicant requests home loan for amount INR 80...,Neutral — application was okay; expects quicke...,Verified documents; requires guarantor for app...,11.747,Positive,Hindu,Delhi,Dwarka,857743,6.940000e+11,9068671773,rohan.verma@example.in,Farmer
1,HDFC100002,HDFC Bank,Rohan Verma,Male,No,0,Graduate,Unemployed,1856,0,899361,240,1,Rural,42,Rejected,707,22272,4.939,Business,9166,1,0,0,NaN,0,No,Sibling,1856,Startup,DEL-001,No,Yes,"NPCI:UPI integrations, SWIFT:International tra...",Applicant requests business loan for amount IN...,Complained about credit score errors and wants...,Escalated to relationship manager for manual C...,40.381,Negative,Hindu,Punjab,Ludhiana,863836,6.330000e+11,9990772625,rohan.verma@example.in,Civil Engineer
2,HDFC100003,HDFC Bank,Aditya Nair,Female,Yes,0,Graduate,Salaried,64553,0,2387748,60,1,Rural,38,Approved,641,774636,0.000,Business,0,2,0,1,NaN,2913766,No,NaN,24557,Private,BLR-003,Yes,Yes,"CIBIL:Credit checks, NPCI:Payments, GSTN:Tax l...",Applicant requests business loan for amount IN...,"Satisfied with application process, but unhapp...",Escalated to relationship manager for manual C...,3.082,Positive,Hindu,Maharashtra,Nagpur,834796,1.660000e+11,9195085016,aditya.nair@example.in,Medical Representative
3,HDFC100004,HDFC Bank,Ananya Joshi,Male,No,0,Graduate,Salaried,88450,0,658856,12,1,Semiurban,32,Approved,677,1061400,0.301,Personal,26613,1,0,3,NaN,3488244,No,Friend,36750,Startup,KOL-004,Yes,Yes,"NPCI:UPI integrations, SWIFT:International tra...",Applicant mentions dispute with property valua...,Complained about credit score errors and wants...,Escalated to relationship manager for manual C...,0.621,Negative,Hindu,Gujarat,Vadodara,438590,5.528183e+10,9179335548,ananya.joshi@example.in,Marketing Executive
4,HDFC100005,HDFC Bank,Harpreet Singh,Male,Yes,3,Graduate,Self-Employed,9539,0,198671,36,0,Semiurban,35,Approved,594,114468,0.000,Personal,0,0,0,2,Agriculture,472179,No,Parent,3920,Public,BLR-003,Yes,Yes,"NPCI:UPI integrations, SWIFT:International tra...",Applicant mentions dispute with property valua...,Appreciative of online service and prompt comm...,Verified documents; requires guarantor for app...,1.736,Neutral,Sikh,West Bengal,Kolkata,495224,1.560000e+11,9795137116,harpreet.singh@example.in,Shopkeeper

In [4]:
print("Rows and Columns:")
df.shape

Rows and Columns:

(1000, 47)

In [5]:
df.columns.tolist()

['Loan_ID',
 'Bank',
 'Customer_Name',
 'Gender',
 'Married',
 'Dependents',
 'Education',
 'Employment_Status',
 'Applicant_Income',
 'Coapplicant_Income',
 'Loan_Amount',
 'Loan_Term_Months',
 'Credit_History',
 'Property_Area',
 'Age',
 'Loan_Status',
 'CIBIL_Score',
 'Annual_Household_Income',
 'Debt_to_Income_Ratio',
 'Purpose_of_Loan',
 'Existing_EMIs',
 'Number_of_Previous_Loans',
 'Default_History_Count',
 'Employment_Length_Years',
 'Business_Type',
 'Asset_Value',
 'Guarantor',
 'Co-signer_Relationship',
 'Monthly_Expense',
 'Organization_Type',
 'Region_Branch',
 'Mobile_Verified',
 'Email_Verified',
 'Institutional_Relationships',
 'Application_Text',
 'Customer_Feedback',
 'Agent_Notes',
 'Loan_to_Annual_Income',
 'Customer_Sentiment',
 'Religion',
 'State',
 'City',
 'PIN_Code',
 'Aadhaar_Synthetic',
 'Phone_Number',
 'Email',
 'Occupation']

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 47 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   Loan_ID                      1000 non-null   object
 1   Bank                         1000 non-null   object
 2   Customer_Name                1000 non-null   object
 3   Gender                       1000 non-null   object
 4   Married                      1000 non-null   object
 5   Dependents                   1000 non-null   int64
 6   Education                    1000 non-null   object
 7   Employment_Status            1000 non-null   object
 8   Applicant_Income             1000 non-null   int64
 9   Coapplicant_Income           1000 non-null   int64
 10  Loan_Amount                  1000 non-null   int64
 11  Loan_Term_Months             1000 non-null   int64
 12  Credit_History               1000 non-null   int64
 13  Property_Area                1000 non-null   object
 14  Age                          1000 non-null   int64
 15  Loan_Status                  1000 non-null   object
 16  CIBIL_Score                  1000 non-null   int64
 17  Annual_Household_Income      1000 non-null   int64
 18  Debt_to_Income_Ratio         1000 non-null   float64
 19  Purpose_of_Loan              1000 non-null   object
 20  Existing_EMIs                1000 non-null   int64
 21  Number_of_Previous_Loans     1000 non-null   int64
 22  Default_History_Count        1000 non-null   int64
 23  Employment_Length_Years      1000 non-null   int64
 24  Business_Type                201 non-null    object
 25  Asset_Value                  1000 non-null   int64
 26  Guarantor                    1000 non-null   object
 27  Co-signer_Relationship       766 non-null    object
 28  Monthly_Expense              1000 non-null   int64
 29  Organization_Type            1000 non-null   object
 30  Region_Branch                1000 non-null   object
 31  Mobile_Verified              1000 non-null   object
 32  Email_Verified               1000 non-null   object
 33  Institutional_Relationships  1000 non-null   object
 34  Application_Text             1000 non-null   object
 35  Customer_Feedback            1000 non-null   object
 36  Agent_Notes                  1000 non-null   object
 37  Loan_to_Annual_Income        1000 non-null   float64
 38  Customer_Sentiment           1000 non-null   object
 39  Religion                     1000 non-null   object
 40  State                        1000 non-null   object
 41  City                         1000 non-null   object
 42  PIN_Code                     1000 non-null   int64
 43  Aadhaar_Synthetic            1000 non-null   float64
 44  Phone_Number                 1000 non-null   int64
 45  Email                        1000 non-null   object
 46  Occupation                   1000 non-null   object
dtypes: float64(3), int64(17), object(27)
memory usage: 367.3+ KB

In [10]:
null_values = df.isnull().sum()

null_values[null_values > 0]

Business_Type             799
Co-signer_Relationship    234
dtype: int64

In [11]:
df.duplicated().sum()

np.int64(0)

In [12]:
df.describe()

,Dependents,Applicant_Income,Coapplicant_Income,Loan_Amount,Loan_Term_Months,Credit_History,Age,CIBIL_Score,Annual_Household_Income,Debt_to_Income_Ratio,Existing_EMIs,Number_of_Previous_Loans,Default_History_Count,Employment_Length_Years,Asset_Value,Monthly_Expense,Loan_to_Annual_Income,PIN_Code,Aadhaar_Synthetic,Phone_Number
count,1000.000000,1000.000000,1000.00000,1.000000e+03,1000.000000,1000.00000,1000.000000,1000.00000,1.000000e+03,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1.000000e+03,1000.000000,1000.000000,1000.00000,1.000000e+03,1.000000e+03
mean,0.849000,42430.057000,9727.11400,2.216713e+06,159.132000,0.72300,34.412000,653.01300,6.258861e+05,148.118157,18173.390000,0.865000,0.147000,2.434000,1.908042e+06,23603.427000,10.163103,509976.40800,4.853217e+11,9.500193e+09
std,0.964951,28133.210769,20568.25945,2.635021e+06,127.056704,0.44774,8.572616,73.83654,4.724545e+05,1974.599103,16298.460525,0.911925,0.499641,2.791673,1.481451e+06,18054.598235,25.415631,289145.26265,2.925311e+11,2.875105e+08
min,0.000000,0.000000,0.00000,1.884000e+03,12.000000,0.00000,18.000000,384.00000,0.000000e+00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000e+00,0.000000,0.003000,622.00000,2.589553e+08,9.002443e+09
25%,0.000000,18260.000000,0.00000,3.729465e+05,36.000000,0.00000,28.000000,605.75000,2.639520e+05,0.031000,1741.750000,0.000000,0.000000,0.000000,7.424400e+05,9159.250000,0.645750,263067.50000,2.190000e+11,9.254018e+09
50%,1.000000,40675.500000,0.00000,9.720460e+05,120.000000,1.00000,35.000000,654.00000,5.512440e+05,0.332000,16289.500000,1.000000,0.000000,2.000000,1.634312e+06,20787.500000,2.309000,517643.50000,4.735000e+11,9.498140e+09
75%,2.000000,61037.250000,7956.50000,3.315038e+06,300.000000,1.00000,40.000000,704.00000,8.565480e+05,0.795000,29718.500000,1.000000,0.000000,3.000000,2.726302e+06,33067.750000,8.326750,756922.00000,7.300000e+11,9.750462e+09
max,3.000000,149266.000000,123461.00000,1.379096e+07,360.000000,1.00000,66.000000,878.00000,2.555340e+06,38342.000000,82436.000000,5.000000,3.000000,15.000000,7.742001e+06,97762.000000,269.754000,998910.00000,9.990000e+11,9.999102e+09

In [13]:
categorical_cols = df.select_dtypes(
    include="object"
).columns

categorical_cols

Index(['Loan_ID', 'Bank', 'Customer_Name', 'Gender', 'Married', 'Education',
       'Employment_Status', 'Property_Area', 'Loan_Status', 'Purpose_of_Loan',
       'Business_Type', 'Guarantor', 'Co-signer_Relationship',
       'Organization_Type', 'Region_Branch', 'Mobile_Verified',
       'Email_Verified', 'Institutional_Relationships', 'Application_Text',
       'Customer_Feedback', 'Agent_Notes', 'Customer_Sentiment', 'Religion',
       'State', 'City', 'Email', 'Occupation'],
      dtype='object')

In [16]:
for col in categorical_cols:
    print("\n")
    print(col)
    print(df[col].nunique())

Loan_ID
1000


Bank
1


Customer_Name
41


Gender
3


Married
2


Education
2


Employment_Status
4


Property_Area
3


Loan_Status
2


Purpose_of_Loan
7


Business_Type
6


Guarantor
2


Co-signer_Relationship
5


Organization_Type
5


Region_Branch
7


Mobile_Verified
2


Email_Verified
2


Institutional_Relationships
5


Application_Text
222


Customer_Feedback
5


Agent_Notes
5


Customer_Sentiment
3


Religion
5


State
10


City
29


Email
41


Occupation
18

In [17]:
df["Loan_Status"].value_counts()

Loan_Status
Approved    653
Rejected    347
Name: count, dtype: int64

In [19]:
numerical_cols = df.select_dtypes(
    include=np.number
).columns

numerical_cols

Index(['Dependents', 'Applicant_Income', 'Coapplicant_Income', 'Loan_Amount',
       'Loan_Term_Months', 'Credit_History', 'Age', 'CIBIL_Score',
       'Annual_Household_Income', 'Debt_to_Income_Ratio', 'Existing_EMIs',
       'Number_of_Previous_Loans', 'Default_History_Count',
       'Employment_Length_Years', 'Asset_Value', 'Monthly_Expense',
       'Loan_to_Annual_Income', 'PIN_Code', 'Aadhaar_Synthetic',
       'Phone_Number'],
      dtype='object')

In [20]:
df[numerical_cols].describe()

,Dependents,Applicant_Income,Coapplicant_Income,Loan_Amount,Loan_Term_Months,Credit_History,Age,CIBIL_Score,Annual_Household_Income,Debt_to_Income_Ratio,Existing_EMIs,Number_of_Previous_Loans,Default_History_Count,Employment_Length_Years,Asset_Value,Monthly_Expense,Loan_to_Annual_Income,PIN_Code,Aadhaar_Synthetic,Phone_Number
count,1000.000000,1000.000000,1000.00000,1.000000e+03,1000.000000,1000.00000,1000.000000,1000.00000,1.000000e+03,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1.000000e+03,1000.000000,1000.000000,1000.00000,1.000000e+03,1.000000e+03
mean,0.849000,42430.057000,9727.11400,2.216713e+06,159.132000,0.72300,34.412000,653.01300,6.258861e+05,148.118157,18173.390000,0.865000,0.147000,2.434000,1.908042e+06,23603.427000,10.163103,509976.40800,4.853217e+11,9.500193e+09
std,0.964951,28133.210769,20568.25945,2.635021e+06,127.056704,0.44774,8.572616,73.83654,4.724545e+05,1974.599103,16298.460525,0.911925,0.499641,2.791673,1.481451e+06,18054.598235,25.415631,289145.26265,2.925311e+11,2.875105e+08
min,0.000000,0.000000,0.00000,1.884000e+03,12.000000,0.00000,18.000000,384.00000,0.000000e+00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000e+00,0.000000,0.003000,622.00000,2.589553e+08,9.002443e+09
25%,0.000000,18260.000000,0.00000,3.729465e+05,36.000000,0.00000,28.000000,605.75000,2.639520e+05,0.031000,1741.750000,0.000000,0.000000,0.000000,7.424400e+05,9159.250000,0.645750,263067.50000,2.190000e+11,9.254018e+09
50%,1.000000,40675.500000,0.00000,9.720460e+05,120.000000,1.00000,35.000000,654.00000,5.512440e+05,0.332000,16289.500000,1.000000,0.000000,2.000000,1.634312e+06,20787.500000,2.309000,517643.50000,4.735000e+11,9.498140e+09
75%,2.000000,61037.250000,7956.50000,3.315038e+06,300.000000,1.00000,40.000000,704.00000,8.565480e+05,0.795000,29718.500000,1.000000,0.000000,3.000000,2.726302e+06,33067.750000,8.326750,756922.00000,7.300000e+11,9.750462e+09
max,3.000000,149266.000000,123461.00000,1.379096e+07,360.000000,1.00000,66.000000,878.00000,2.555340e+06,38342.000000,82436.000000,5.000000,3.000000,15.000000,7.742001e+06,97762.000000,269.754000,998910.00000,9.990000e+11,9.999102e+09

In [21]:
with open(
    "data_understanding_report.txt",
    "w"
) as file:

    file.write(
        f"Dataset Shape: {df.shape}"
    )